# prompt
PS1='%B%F{blue}- %F{green}%n@%M %F{yellow}[%D %T] %F{blue}%d
%F{blue}- %#%b%f '

# ls colors
alias ls="ls --color"

# PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"

# Run Plasma
if [ $(tty) = "/dev/tty1" ]; then
    startplasma-wayland
fi
