# enable auto-completion
autoload -U compinit
compinit

# completion style
zstyle ':completion:*' menu select

# use cache for completion
zstyle ':completion::complete:*' use-cache 1

# enable auto-correction
setopt correctall

# enable advanced prompt support
autoload -U promptinit
promptinit

# set prompt to gentoo's one
prompt gentoo

# enable history
export HISTSIZE=2000
export HISTFILE="$HOME/.cache/zsh_history"

# save history
export SAVEHIST=$HISTSIZE

# history ignore duplicates
setopt hist_ignore_all_dups

# easier cd
setopt autocd

# ls colors
alias ls="ls --color"

# apply QT theme with qt5ct and qt6ct
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct

# PATH
export PATH="$PATH:$HOME"/.local/bin

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# Run Hyprland
if [ $(tty) = "/dev/tty1" ]; then
    Hyprland
fi
