# enable auto-completion
autoload -U compinit
compinit

# completion style
zstyle ':completion:*' menu select

# use cache for completion
zstyle ':completion::complete:*' use-cache 1

# enable auto-correction
setopt correctall

# prompt
PS1='%B%F{blue}- %F{green}%n@%M %F{yellow}[%D %T] %F{blue}%d
%F{blue}- %#%b%f '


### BINDINGS ###

# use emacs bindings
bindkey -e 

# bind home and end
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line


# enable history
export HISTSIZE=2000
export HISTFILE="$HOME/.cache/zsh_history"

# save history
export SAVEHIST=$HISTSIZE

# history ignore duplicates
setopt hist_ignore_all_dups

# easier cd
setopt autocd

# ls colors
alias ls="ls --color"

# PATH
export PATH="$PATH:$HOME"/.local/bin

# Run Plasma
if [ $(tty) = "/dev/tty1" ]; then
    startplasma-wayland
fi
