require('vis')                                                                                                                                                                                               
vis.events.subscribe(vis.events.INIT, function()
  vis:command('set ignorecase on')
  vis:command('set expandtab on')
  vis:command('set tabwidth 2')
  vis:command('set theme solarized')
end)                                                                                                                                                                                           
vis.events.subscribe(vis.events.WIN_OPEN, function(win)
  vis:command('set relativenumbers on')
end)     
